using TCFModManager.Core.Markup;
using Xunit;

namespace TCFModManager.Core.Tests;

// Each sample is a real 37x21 file made with ImageMagick, in every format and variant the reader
// handles (the BMP cut to its first 600 bytes - the header is all that is read).
public class ImageHeaderTests
{
    [Theory]
    [InlineData("Png", "iVBORw0KGgoAAAANSUhEUgAAACUAAAAVAQMAAAD7KrXtAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGUExURf8AAP///0EdNBEAAAABYktHRAH/Ai3eAAAAB3RJTUUH6gkZAhIgGxRsVQAAAAxJREFUCNdjYBhIAAAAfgAB/bU3UgAAAABJRU5ErkJggg==")]
    [InlineData("Gif", "R0lGODlhJQAVAPAAAP8AAAAAACH5BAAAAAAAIf8LSW1hZ2VNYWdpY2sOZ2FtbWE9MC40NTQ1NDUALAAAAAAlABUAAAIahI+py+0Po5y02ouz3rz7D4biSJbmiaYqWgAAOw==")]
    [InlineData("Jpeg", "/9j/4AAQSkZJRgABAQAAAAAAAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAVACUDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFgEBAQEAAAAAAAAAAAAAAAAAAAcJ/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AnRDGqYAAAAAAAAAAAAAD/9k=")]
    [InlineData("ProgressiveJpeg", "/9j/4AAQSkZJRgABAQAAAAAAAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wgARCAAVACUDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAWAQEBAQAAAAAAAAAAAAAAAAAABgj/2gAMAwEAAhADEAAAAZzC6pAAAAAAA//EABQQAQAAAAAAAAAAAAAAAAAAADD/2gAIAQEAAQUCf//EABQRAQAAAAAAAAAAAAAAAAAAADD/2gAIAQMBAT8Bf//EABQRAQAAAAAAAAAAAAAAAAAAADD/2gAIAQIBAT8Bf//EABQQAQAAAAAAAAAAAAAAAAAAADD/2gAIAQEABj8Cf//EABQQAQAAAAAAAAAAAAAAAAAAADD/2gAIAQEAAT8hf//aAAwDAQACAAMAAAAQ/wD/AP8A/wD/AP8A/8QAFBEBAAAAAAAAAAAAAAAAAAAAMP/aAAgBAwEBPxB//8QAFBEBAAAAAAAAAAAAAAAAAAAAMP/aAAgBAgEBPxB//8QAFBABAAAAAAAAAAAAAAAAAAAAMP/aAAgBAQABPxB//9k=")]
    [InlineData("Bmp", "Qk26CQAAAAAAAIoAAAB8AAAAJQAAABUAAAABABgAAAAAADAJAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAD/AAD/AAAAAAAA/0JHUnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAA/wAAAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAAA/wAA/wAA/wAA/wAA")]
    [InlineData("WebpLossy", "UklGRk4AAABXRUJQVlA4IEIAAABQAwCdASolABUAPpFGnkslo6KhpWgAsBIJZwDO3oAAK/fDcAD+7qY//2LOWwLx//7nA/7nA/7nA/jbB+29aoAAAAA=")]
    [InlineData("WebpLossless", "UklGRhwAAABXRUJQVlA4TA8AAAAvJAAFAAcQ/Y/+ByKi/wEA")]
    [InlineData("WebpExtended", "UklGRnIAAABXRUJQVlA4WAoAAAAQAAAAJAAAFAAAQUxQSAoAAAABB1DAiAhERP8DVlA4IEIAAABQAwCdASolABUAPpFGnkslo6KhpWgAsBIJZwDO3oAAK/fDcAD+7qY//2LOWwLx//7nA/7nA/7nA/jbB+29aoAAAAA=")]
    public void Reads_the_width_from_the_header(string format, string base64)
    {
        Assert.True(ImageHeader.Width(Convert.FromBase64String(base64)) == 37, format);
    }

    [Fact]
    public void Unknown_or_cut_short_bytes_give_no_width()
    {
        Assert.Null(ImageHeader.Width([]));
        Assert.Null(ImageHeader.Width(new byte[64]));
        Assert.Null(ImageHeader.Width("<html><body>not a picture</body></html>"u8));
    }

    // Two frames, the second with a colour table of its own; and the same picture as one frame.
    private const string TwoFrames = "R0lGODlhBAADAPAAAP8AAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQAAAAAACH/C0ltYWdlTWFnaWNrDmdhbW1hPTAuNDU0NTQ1ACwAAAAABAADAAACA4SPVgAh+QQAAAAAACH/C0ltYWdlTWFnaWNrDmdhbW1hPTAuNDU0NTQ1ACwAAAAABAADAIAAAP8AAAACA4SPVgA7";
    private const string OneFrame = "R0lGODlhBAADAPAAAP8AAAAAACH5BAAAAAAAIf8LSW1hZ2VNYWdpY2sOZ2FtbWE9MC40NTQ1NDUALAAAAAAEAAMAAAIDhI9WADs=";

    [Fact]
    public void A_gif_of_several_frames_is_an_animation()
    {
        Assert.True(ImageHeader.IsAnimatedGif(Convert.FromBase64String(TwoFrames)));
    }

    [Fact]
    public void A_gif_of_one_frame_is_a_still()
    {
        Assert.False(ImageHeader.IsAnimatedGif(Convert.FromBase64String(OneFrame)));
    }

    [Fact]
    public void A_cut_short_gif_or_another_format_is_not_an_animation()
    {
        var bytes = Convert.FromBase64String(TwoFrames);

        Assert.False(ImageHeader.IsAnimatedGif(bytes.AsSpan(0, 60)));
        Assert.False(ImageHeader.IsAnimatedGif(new byte[] { 0x89, (byte)'P', (byte)'N', (byte)'G', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }));
        Assert.False(ImageHeader.IsAnimatedGif([]));
    }
}
